### ISSUE TITLE
Cannot get random pokemon to work

### ISSUE THREAD

**Issue by xarDeves** [talwat/pokeget-rs#6] opened 2024-01-08 11:55 UTC
Hello, i cloned your project while also downloading all the necessary sprites, i am able to run the program and successfully display pokemon. (Note that i can only do that by name).

The problem i specifically face has to do with random pokemon, it seems that the path is wrong when passing in "random", both from the terminal and hardcoded.

The code i am operating on has been slightly changed, however this was an issue from the get-go. This issue is raised as a means for feedback on whether the "random" functionality is actually working, so as to determine whether my filetree/configuration is broken

P.S. i am working on windows.

Thank you.

**Comment by talwat** [comment] 2024-01-08 12:31
I haven't tested on windows, which could be the reason. I'll check it out, thanks. Did you make sure that the pokesprite submodule is there?

**Comment by xarDeves** [comment] 2024-01-08 13:24
yes, the paths are correct, and it is especially weird behaviour since when
a pokemon name is passed it works.

i will test on linux as well...

**Comment by talwat** [comment] 2024-01-08 19:10
`random` works fine on my end, can you try using `cargo install` to install pokeget instead?

**Comment by talwat** [comment] 2024-01-08 21:12
Why not just clone with recursive submodules, like stated in the instructions? That should work, since there's probably an issue with nested directories. Or, there's a random newline being inserted somewhere? You said you made modifications which doesn't exactly inspire confidence, but you shouldn't need to change the path or anything.

> in the installed version random works

Yeah, my guess is rust-embed is stupid or whatever.

**Comment by xarDeves** [comment] 2024-01-08 21:57
thank you for your quick responses, i will look into it further and come
back to the issue if i find a fix

**Comment by xarDeves** [comment] 2024-01-10 14:38
Compiled and run the release build in both windows and linux.
The issue persists, when addressing a pokemon with `random`, or any `id` i get "pokemon not found".

(used recursive cloning)

**Comment by talwat** [comment] 2024-01-10 15:23
That's super strange, does `cargo run random` work? I'll try to reproduce the issue in a VM or something like that.

**Comment by xarDeves** [comment] 2024-01-10 15:36
`cargo run random` and `cargo run {id}` do not work (in both linux and windows).

In both platforms, using both `cargo run` and the release build the printed path is:
`.pngsprite/pokemon-gen8/regular/{correct pokemon name}`

I have tried different ways to apply the `format!` macro and also used `std::path` but to no avail, that ".png" always ends up in the beginning of the string, replacing the first four characters.

**Comment by talwat** [comment] 2024-01-10 15:50
This is a *really* weird bug...

**Comment by talwat** [comment] 2024-01-11 10:24
Could you make a repository with your current setup? Then I'll see if I can reproduce it, since it works fine for me.

**Comment by xarDeves** [comment] 2024-01-11 10:28
The tests i've been running were done with your recursively cloned repo (latest commit of course). Nothing at all changed.

**Comment by talwat** [comment] 2024-01-11 10:34
What version of rust are you using? Maybe it's that?

**Comment by xarDeves** [comment] 2024-01-11 10:41
the pain...
rust v1.75.0 (windows and linux)

Fyi my linux installation uses hyprland, maybe that messes things up ? but then again the exact same thing happens on windows.

**Comment by xarDeves** [comment] 2024-01-13 19:27
I just issued a pull request that fixed the bug.

Tested on windows and linux.
Tested debug and release build.

**Comment by talwat** [comment] 2024-01-14 10:24
Merged 👍, thanks so much!

**Closed by talwat** 2024-01-14 10:24 UTC
